
sudo: enabled
language: python
python: 
  - "3.6"

install:
  - pip install --upgrade -r requirements.txt
  - python setup.py develop

script:
  - py.test --doctest-modules --disable-warnings licpy

